name: Build landingpage

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v6.3.0
      with:
        python-version: 3.12
        # regenerate.sh uses a venv, so this is useless
        # cache: pip
        # pip-install: -r requirements.txt

    - name: Cache
      uses: actions/cache@v5.1.0
      with:
        key: ${{ hashFiles('bin/*') }}
        path: |
          assets/js/tailwinds.js
          assets/fonts/fontawesome.zip
          assets/fonts/source-sans
          assets/tailwindcss-linux
          assets/js/chart.js

    - name: Build
      run: |
        bin/regenerate.sh

    - name: Push the artifact
      id: artifact-upload-step
      uses: actions/upload-artifact@v7.0.1
      with:
        name: Built landingpage
        path: dist

    - name: Set artifact url
      id: set-artifact-url
      run: echo artifact_url=${{github.api_url}}/repos/${{github.repository}}/actions/artifacts/${{steps.artifact-upload-step.outputs.artifact-id}}/zip >> $GITHUB_OUTPUT

    - name: Ping Landingpage server
      uses: distributhor/workflow-webhook@v3
      with:
        webhook_url: http://yunohost.org/github
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        webhook_type: json-extended
        data: '{"artifact_url": "${{ steps.set-artifact-url.outputs.artifact_url }}"}'
